apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ramaapp
  name: ramaapp-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ramaapp
    spec:
      containers:
      - image: kprad/projimg
        name: ramaapp
        ports:
        - name: ramaapp
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ramaapp
  name: ramaapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: ramaapp
